### ISSUE TITLE
3-9-7-5 tuzağına düşmemek için aksiyon alınması

### ISSUE THREAD

**Issue by aliorhun** [0x7000/tictactoe#1]
3-9-7-5 tuzağına düşmemek için aksiyon alınabilir. ilk hamlede (3 eklenmesi) 2 dışındaki her yere koymak daha mantıklı. Hele ki 9'a koyması gerekir bile denebilir. :)

**Comment by 0x7000** [comment]
son güncelleme ile ortadan başlayarak ilerliyor düzelttim "galiba"
